const navLinks = [
  {
    name: "HOME",
    href: "/",
  },
  {
    name: "ABOUT US",
    href: "/about-us",
  },
  {
    name: "PROPERTIES",
    href: "/properties",
  },
  {
    name: "CONTACT US",
    href: "/contact-us",
  },
];

const popularProperties: Property[] = [
  {
    id: "1",
    title: "Beautiful House",
    description: "This is a beautiful house",
    price: 100000,
    location: "Nagaon, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 1200,
    ownerName: "Angel Saikia",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "2",
    title: "Cozy Apartment",
    description: "A modern apartment in the heart of the city",
    price: 75000,
    location: "Guwahati, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    garages: 0,
    area: 800,
    ownerName: "Rahul Sharma",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "3",
    title: "Riverside Villa",
    description: "Luxurious villa with a stunning river view",
    price: 250000,
    location: "Dibrugarh, Assam",
    images: ["/images/property_3.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    area: 2500,
    ownerName: "Priya Borah",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "4",
    title: "Charming Cottage",
    description: "A quaint cottage surrounded by nature",
    price: 80000,
    location: "Jorhat, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    area: 1000,
    ownerName: "Biplab Das",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "5",
    title: "Modern Townhouse",
    description: "Sleek townhouse with contemporary design",
    price: 150000,
    location: "Silchar, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 1800,
    ownerName: "Nandita Roy",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "6",
    title: "Hillside Retreat",
    description: "Peaceful property with panoramic hill views",
    price: 200000,
    location: "Haflong, Assam",
    images: ["/images/property_3.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 2000,
    ownerName: "Manoj Gogoi",
    ownerPhoto: "/images/profile_1.jpg",
  },
];

const recentProperties: Property[] = [
  {
    id: "1",
    title: "Beautiful House",
    description: "This is a beautiful house",
    price: 100000,
    location: "Nagaon, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 1200,
    ownerName: "Angel Saikia",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "2",
    title: "Cozy Cottage",
    description: "Charming cottage with a lovely garden",
    price: 85000,
    location: "Jorhat, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    area: 900,
    ownerName: "Rina Das",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "3",
    title: "Luxury Villa",
    description: "Spacious villa with modern amenities",
    price: 300000,
    location: "Guwahati, Assam",
    images: ["/images/property_3.jpg"],
    bedrooms: 5,
    bathrooms: 4,
    garages: 2,
    area: 3500,
    ownerName: "Arun Sharma",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "4",
    title: "Urban Apartment",
    description: "Stylish apartment in the heart of the city",
    price: 120000,
    location: "Dibrugarh, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 2,
    bathrooms: 2,
    garages: 1,
    area: 1100,
    ownerName: "Priya Sen",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "5",
    title: "Suburban Home",
    description: "Comfortable home in a quiet neighborhood",
    price: 95000,
    location: "Tezpur, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 1300,
    ownerName: "Rakesh Bora",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "6",
    title: "Beachside Bungalow",
    description: "Relaxing bungalow with ocean views",
    price: 250000,
    location: "Hailakandi, Assam",
    images: ["/images/property_3.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    area: 2200,
    ownerName: "Sunita Das",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "7",
    title: "Mountain Cabin",
    description: "Cozy cabin with stunning mountain views",
    price: 180000,
    location: "Diphu, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    area: 1500,
    ownerName: "Anil Saikia",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "8",
    title: "Downtown Loft",
    description: "Modern loft in a vibrant downtown area",
    price: 140000,
    location: "Silchar, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    area: 1000,
    ownerName: "Meera Dutta",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "9",
    title: "Country Estate",
    description: "Expansive estate with beautiful landscapes",
    price: 400000,
    location: "Tinsukia, Assam",
    images: ["/images/property_3.jpg"],
    bedrooms: 6,
    bathrooms: 5,
    garages: 3,
    area: 5000,
    ownerName: "Rajiv Hazarika",
    ownerPhoto: "/images/profile_1.jpg",
  },
  {
    id: "10",
    title: "Historic Mansion",
    description: "Elegant mansion with historical significance",
    price: 350000,
    location: "Sivasagar, Assam",
    images: ["/images/property_1.jpg"],
    bedrooms: 5,
    bathrooms: 4,
    garages: 2,
    area: 4000,
    ownerName: "Kavita Phukan",
    ownerPhoto: "/images/profile_2.jpg",
  },
  {
    id: "11",
    title: "Riverside Cottage",
    description: "Charming cottage by the river",
    price: 95000,
    location: "Majuli, Assam",
    images: ["/images/property_2.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    area: 800,
    ownerName: "Bikash Kalita",
    ownerPhoto: "/images/profile_1.jpg",
  },
];

export { navLinks, popularProperties, recentProperties };
